### ISSUE TITLE
EasyAdmin

### ISSUE THREAD

**Issue by tugrul** [EvercodeLab/DependentSelectBundle#14]
How can i use in EasyAdmin?

My EasyAdmin config
```yaml
easy_admin:
    Branch:
            class: App\Entity\Branch
            form:
                fields:
                    - title
                    - institution
                    - slug
                    - {property: latitude, type_options: {scale: 8} }
                    - {property: longitude, type_options: {scale: 8} }
                    - description
                    - city
                    -
                        property: district
                        type: Evercode\DependentSelectBundle\Form\Type\DependentFilteredEntityType
                        type_options:
                            entity_alias: district_by_city
                            empty_value: 'Choose District'
                            parent_field: city
                    - zip
                    - address
                    -
                        property: branchInfos
                        type: collection
                        type_options:
                            entry_type: App\Form\BranchInfoType
                            by_reference: false
```

But error occurs
```
Could not load type "form": class does not exist.
```
